server:
  port: 8181

spring:
  application:
    name: payments-app

integrations:
  executors:
    products-executor-client:
      url: "http://localhost:8282/products"
      connect-timeout: 1s
      read-timeout: 30s
